Repository concertypin/ArisuTalk, pull requests merged in 2025-08, with the labels that each got.

#13 ci: Add AI Issue Labeler workflow
  .github/workflows/issue.yml
Labels: c:meta, t:new feature

#16 feat: Add PWA support with icons and manifest file
  frontend/index.html
  frontend/static/icon_192.png
  frontend/static/icon_512.png
  frontend/static/manifest.webmanifest
Labels: c:frontend, t:new feature

#18 feat: Restructure UI, add i18n, and improve code quality
  .gitignore
  README.md
  backend/app/build.gradle.kts
  backend/app/src/main/kotlin/org/example/App.kt
  docs/ARCHITECTURE.md
  docs/I18N.md
  frontend/README.md
  frontend/index.html
  frontend/package.json
  frontend/src/api/apiManager.js
  frontend/src/api/claude.js
  frontend/src/api/customopenai.js
  frontend/src/api/gemini.js
  frontend/src/api/grok.js
  frontend/src/api/openai.js
  frontend/src/api/openrouter.js
  frontend/src/api/promptBuilder.js
  frontend/src/api/prompts.js
  frontend/src/components/Avatar.js
  frontend/src/components/CharacterModal.js
  frontend/src/components/ConfirmationModal.js
  frontend/src/components/DebugLogsModal.js
  frontend/src/components/DesktopSettingsUI.js
  frontend/src/components/GroupChat.js
  frontend/src/components/MainChat.js
  frontend/src/components/MasterPasswordModal.js
  frontend/src/components/MobileSettingsModal.js
  frontend/src/components/PromptModal.js
  frontend/src/components/SettingsModal.js
  frontend/src/components/SettingsRouter.js
  frontend/src/components/Sidebar.js
  frontend/src/components/settings/panels/APISettingsPanel.js
  frontend/src/components/settings/panels/AdvancedSettingsPanel.js
  frontend/src/components/settings/panels/AppearanceSettingsPanel.js
  frontend/src/components/settings/panels/CharacterDefaultsPanel.js
  frontend/src/components/settings/panels/DataManagementPanel.js
  frontend/src/constants/providers.js
  frontend/src/defaults.js
  frontend/src/handlers/groupChatHandlers.js
  frontend/src/handlers/mainChatHandlers.js
  frontend/src/handlers/modalHandlers.js
  frontend/src/handlers/sidebarHandlers.js
  frontend/src/i18n.js
  frontend/src/index.js
  frontend/src/language/en.js
  frontend/src/language/ko.js
  frontend/src/storage.js
  frontend/src/ui.js
  frontend/src/utils.js
  frontend/src/utils/crypto.js
  frontend/src/utils/secureStorage.js
  frontend/static/index.css
  pnpm-lock.yaml
Labels: t:bug, t:documentation, c:frontend, t:new feature

#19 docs: Add contribution guidelines and update gitignore/frontend README
  .gitignore
  CONTRIBUTING.ko.md
  CONTRIBUTING.md
  frontend/README.md
  frontend/docs/archetecture.md
  package.json
Labels: t:documentation, c:meta

#26 ci: Change OIDC Client installation to pnpm add
  .github/workflows/production_deploy_to_azure_swa.yml
Labels: c:meta, t:new feature

#27 feat: support docker
  docker-compose.yml
  frontend/Dockerfile
  frontend/vite.config.ts
Labels: c:meta, t:new feature
